version: '3'
services:

    database:
        image: postgres:13
        ports:
            - 5432:5432
        env_file:
            - ./.env
        volumes:
            - data:/var/lib/postgresql/data
        restart: always

volumes:
    data:
