# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/backup_item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_files/backup_item.proto',
  package='backup_item',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dproto_files/backup_item.proto\x12\x0b\x62\x61\x63kup_item\"\xaf\x03\n\nBackupItem\x12?\n\x0fpayment_session\x18\x01 \x01(\x0b\x32&.backup_item.BackupItem.PaymentSession\x12,\n\x05order\x18\x02 \x01(\x0b\x32\x1d.backup_item.BackupItem.Order\x12*\n\x04user\x18\x03 \x01(\x0b\x32\x1c.backup_item.BackupItem.User\x1ap\n\x0ePaymentSession\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x1a\x61\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\x14\n\x0cuser_surname\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x1a\x31\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\tb\x06proto3')
)




_BACKUPITEM_PAYMENTSESSION = _descriptor.Descriptor(
  name='PaymentSession',
  full_name='backup_item.BackupItem.PaymentSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='backup_item.BackupItem.PaymentSession.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='backup_item.BackupItem.PaymentSession.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='backup_item.BackupItem.PaymentSession.order_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='backup_item.BackupItem.PaymentSession.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='backup_item.BackupItem.PaymentSession.amount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='backup_item.BackupItem.PaymentSession.currency', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=328,
)

_BACKUPITEM_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='backup_item.BackupItem.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='backup_item.BackupItem.Order.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='backup_item.BackupItem.Order.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='backup_item.BackupItem.Order.user_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_surname', full_name='backup_item.BackupItem.Order.user_surname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='backup_item.BackupItem.Order.created_at', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=427,
)

_BACKUPITEM_USER = _descriptor.Descriptor(
  name='User',
  full_name='backup_item.BackupItem.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='backup_item.BackupItem.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='backup_item.BackupItem.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='backup_item.BackupItem.User.surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=478,
)

_BACKUPITEM = _descriptor.Descriptor(
  name='BackupItem',
  full_name='backup_item.BackupItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payment_session', full_name='backup_item.BackupItem.payment_session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='backup_item.BackupItem.order', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='backup_item.BackupItem.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BACKUPITEM_PAYMENTSESSION, _BACKUPITEM_ORDER, _BACKUPITEM_USER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=478,
)

_BACKUPITEM_PAYMENTSESSION.containing_type = _BACKUPITEM
_BACKUPITEM_ORDER.containing_type = _BACKUPITEM
_BACKUPITEM_USER.containing_type = _BACKUPITEM
_BACKUPITEM.fields_by_name['payment_session'].message_type = _BACKUPITEM_PAYMENTSESSION
_BACKUPITEM.fields_by_name['order'].message_type = _BACKUPITEM_ORDER
_BACKUPITEM.fields_by_name['user'].message_type = _BACKUPITEM_USER
DESCRIPTOR.message_types_by_name['BackupItem'] = _BACKUPITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BackupItem = _reflection.GeneratedProtocolMessageType('BackupItem', (_message.Message,), dict(

  PaymentSession = _reflection.GeneratedProtocolMessageType('PaymentSession', (_message.Message,), dict(
    DESCRIPTOR = _BACKUPITEM_PAYMENTSESSION,
    __module__ = 'proto_files.backup_item_pb2'
    # @@protoc_insertion_point(class_scope:backup_item.BackupItem.PaymentSession)
    ))
  ,

  Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
    DESCRIPTOR = _BACKUPITEM_ORDER,
    __module__ = 'proto_files.backup_item_pb2'
    # @@protoc_insertion_point(class_scope:backup_item.BackupItem.Order)
    ))
  ,

  User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
    DESCRIPTOR = _BACKUPITEM_USER,
    __module__ = 'proto_files.backup_item_pb2'
    # @@protoc_insertion_point(class_scope:backup_item.BackupItem.User)
    ))
  ,
  DESCRIPTOR = _BACKUPITEM,
  __module__ = 'proto_files.backup_item_pb2'
  # @@protoc_insertion_point(class_scope:backup_item.BackupItem)
  ))
_sym_db.RegisterMessage(BackupItem)
_sym_db.RegisterMessage(BackupItem.PaymentSession)
_sym_db.RegisterMessage(BackupItem.Order)
_sym_db.RegisterMessage(BackupItem.User)


# @@protoc_insertion_point(module_scope)
